import type { Product } from "./product-types";

// Product imagery uses Picsum (https://picsum.photos) with descriptive seeds.
// Replace with generated product shots before final shipping.
const img = (seed: string, w = 1600, h = 1600) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const products: Product[] = [
  {
    id: "p-001",
    slug: "kat-runner-volt",
    name: "Kat Runner 02",
    category: "running",
    gender: "unisex",
    price: 220,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Ink", hex: "#0A0A0B" },
    ],
    primaryHex: "#D7FF1E",
    image: img("katooni-volt-runner", 1600, 1600),
    imageAlt: "Kat Runner 02 in volt, dark studio shot, three-quarter angle.",
    badge: "new-drop",
    popularity: 98,
    releasedAt: "2026-05-12",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Daily mile, full carbon plate, volt sole.",
    weightGrams: 248,
    drop: 8,
  },
  {
    id: "p-002",
    slug: "kat-trail-monolith",
    name: "Kat Trail Monolith",
    category: "trail",
    gender: "unisex",
    price: 245,
    currency: "USD",
    colorways: [
      { name: "Slate", hex: "#3A3D44" },
      { name: "Volt", hex: "#D7FF1E" },
    ],
    primaryHex: "#3A3D44",
    image: img("katooni-trail-monolith", 1600, 1600),
    imageAlt: "Kat Trail Monolith in slate, rugged outsole, dark studio.",
    badge: null,
    popularity: 84,
    releasedAt: "2026-04-02",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Lugged 5 mm outsole, rock plate, gaiter-ready upper.",
    weightGrams: 312,
    drop: 6,
  },
  {
    id: "p-003",
    slug: "kat-track-spike",
    name: "Kat Track Spike",
    category: "track",
    gender: "unisex",
    price: 180,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Carbon", hex: "#161619" },
    ],
    primaryHex: "#161619",
    image: img("katooni-track-spike", 1600, 1600),
    imageAlt: "Kat Track Spike on dark, low-profile competition silhouette.",
    badge: "last-pairs",
    popularity: 71,
    releasedAt: "2026-03-10",
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    short: "Pebax spike plate, removable pyramid pins.",
    weightGrams: 132,
    drop: 4,
  },
  {
    id: "p-004",
    slug: "kat-court-leather",
    name: "Kat Court Leather",
    category: "court",
    gender: "unisex",
    price: 260,
    currency: "USD",
    colorways: [
      { name: "Bone", hex: "#E6E2D6" },
      { name: "Ink", hex: "#0A0A0B" },
    ],
    primaryHex: "#E6E2D6",
    image: img("katooni-court-leather", 1600, 1600),
    imageAlt: "Kat Court Leather in bone, full-grain upper, dark studio.",
    badge: "restock",
    popularity: 76,
    releasedAt: "2026-02-22",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Italian full-grain, hand-lasted, gum rubber outsole.",
    weightGrams: 388,
    drop: 0,
  },
  {
    id: "p-005",
    slug: "kat-knit-pulse",
    name: "Kat Knit Pulse",
    category: "lifestyle",
    gender: "unisex",
    price: 165,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Smoke", hex: "#1F1F24" },
      { name: "Bone", hex: "#E6E2D6" },
    ],
    primaryHex: "#1F1F24",
    image: img("katooni-knit-pulse", 1600, 1600),
    imageAlt: "Kat Knit Pulse in smoke, recycled knit upper, dark studio.",
    badge: "new-drop",
    popularity: 89,
    releasedAt: "2026-05-30",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Recycled knit, sock-fit collar, vulcanized cup sole.",
    weightGrams: 268,
    drop: 6,
  },
  {
    id: "p-006",
    slug: "kat-runner-pro",
    name: "Kat Runner Pro",
    category: "running",
    gender: "unisex",
    price: 285,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Carbon", hex: "#161619" },
    ],
    primaryHex: "#D7FF1E",
    image: img("katooni-runner-pro", 1600, 1600),
    imageAlt: "Kat Runner Pro in volt and carbon, race-day silhouette.",
    badge: null,
    popularity: 92,
    releasedAt: "2026-01-15",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Race-day carbon plate, supercritical foam, 4 mm drop.",
    weightGrams: 198,
    drop: 4,
  },
  {
    id: "p-007",
    slug: "kat-trail-storm",
    name: "Kat Trail Storm",
    category: "trail",
    gender: "unisex",
    price: 235,
    currency: "USD",
    colorways: [
      { name: "Ink", hex: "#0A0A0B" },
      { name: "Volt", hex: "#D7FF1E" },
    ],
    primaryHex: "#0A0A0B",
    image: img("katooni-trail-storm", 1600, 1600),
    imageAlt: "Kat Trail Storm in ink, all-weather upper, dark studio.",
    badge: null,
    popularity: 67,
    releasedAt: "2026-02-04",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "eVent membrane, reinforced toe, 4.5 mm lugs.",
    weightGrams: 328,
    drop: 6,
  },
  {
    id: "p-008",
    slug: "kat-court-low",
    name: "Kat Court Low",
    category: "court",
    gender: "unisex",
    price: 220,
    currency: "USD",
    colorways: [
      { name: "Ink", hex: "#0A0A0B" },
      { name: "Bone", hex: "#E6E2D6" },
    ],
    primaryHex: "#0A0A0B",
    image: img("katooni-court-low", 1600, 1600),
    imageAlt: "Kat Court Low in ink, low-top silhouette, dark studio.",
    badge: "restock",
    popularity: 58,
    releasedAt: "2025-11-08",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Suede and leather low-top, herringbone gum outsole.",
    weightGrams: 372,
    drop: 0,
  },
  {
    id: "p-009",
    slug: "kat-runner-cruiser",
    name: "Kat Runner Cruiser",
    category: "running",
    gender: "unisex",
    price: 195,
    currency: "USD",
    colorways: [
      { name: "Smoke", hex: "#1F1F24" },
      { name: "Volt", hex: "#D7FF1E" },
    ],
    primaryHex: "#1F1F24",
    image: img("katooni-runner-cruiser", 1600, 1600),
    imageAlt: "Kat Runner Cruiser in smoke, cushioned daily trainer.",
    badge: null,
    popularity: 81,
    releasedAt: "2026-03-20",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Max-cushion daily trainer, knit upper, 8 mm drop.",
    weightGrams: 286,
    drop: 8,
  },
  {
    id: "p-010",
    slug: "kat-knit-trail",
    name: "Kat Knit Trail",
    category: "trail",
    gender: "unisex",
    price: 205,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Slate", hex: "#3A3D44" },
    ],
    primaryHex: "#3A3D44",
    image: img("katooni-knit-trail", 1600, 1600),
    imageAlt: "Kat Knit Trail in slate, hybrid trail silhouette.",
    badge: "last-pairs",
    popularity: 49,
    releasedAt: "2025-12-12",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Hybrid road-to-trail knit, 3.5 mm lugs, sock-fit.",
    weightGrams: 274,
    drop: 6,
  },
  {
    id: "p-011",
    slug: "kat-court-mid",
    name: "Kat Court Mid",
    category: "court",
    gender: "unisex",
    price: 240,
    currency: "USD",
    colorways: [
      { name: "Bone", hex: "#E6E2D6" },
      { name: "Ink", hex: "#0A0A0B" },
    ],
    primaryHex: "#E6E2D6",
    image: img("katooni-court-mid", 1600, 1600),
    imageAlt: "Kat Court Mid in bone, mid-top silhouette, dark studio.",
    badge: null,
    popularity: 64,
    releasedAt: "2026-01-28",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Mid-cut leather, padded collar, vulcanized gum sole.",
    weightGrams: 412,
    drop: 0,
  },
  {
    id: "p-012",
    slug: "kat-lifestyle-cruise",
    name: "Kat Cruise",
    category: "lifestyle",
    gender: "unisex",
    price: 145,
    currency: "USD",
    colorways: [
      { name: "Bone", hex: "#E6E2D6" },
      { name: "Ink", hex: "#0A0A0B" },
      { name: "Volt", hex: "#D7FF1E" },
    ],
    primaryHex: "#0A0A0B",
    image: img("katooni-cruise", 1600, 1600),
    imageAlt: "Kat Cruise in ink, low-profile lifestyle sneaker.",
    badge: null,
    popularity: 73,
    releasedAt: "2026-04-18",
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Canvas upper, vulcanized sole, all-day comfort.",
    weightGrams: 296,
    drop: 0,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedDrop(): Product {
  // The new-drop with the highest popularity is the current featured drop.
  const newDrops = products.filter((p) => p.badge === "new-drop");
  const pool = newDrops.length > 0 ? newDrops : products;
  return [...pool].sort((a, b) => b.popularity - a.popularity)[0];
}

export function getStorePreview(): Product[] {
  return [...products]
    .sort((a, b) => b.popularity - a.popularity)
    .slice(0, 4);
}
