import type { Product } from "./product-types";
import { productImageSvg } from "./product-svg";

// Real photography lives in /public/products/{slug}.png. Products not in
// this map fall back to the SVG generator so the catalog stays complete.
const REAL_IMAGES: Record<string, string> = {
  "kat-runner-volt": "/products/kat-runner-volt.png",
  "kat-runner-cruiser": "/products/kat-runner-cruiser.png",
};

const img = (id: string): string => {
  if (REAL_IMAGES[id]) return REAL_IMAGES[id];
  const partial: Product = {
    id,
    slug: id,
    name: id,
    brand: "katooni",
    category: "running",
    gender: "unisex",
    price: 0,
    currency: "USD",
    colorways: [{ name: "Volt", hex: "#D7FF1E" }],
    primaryHex: "#D7FF1E",
    image: "",
    imageAlt: "",
    badge: null,
    popularity: 0,
    releasedAt: "2026-01-01",
    sizes: [42],
    short: "",
    weightGrams: 0,
    drop: 0,
  };
  return productImageSvg(partial, 1600, 1600);
};

export const products: Product[] = [
  {
    id: "p-001",
    slug: "kat-runner-volt",
    name: "Kat Runner 02",
    brand: "katooni",
    category: "running",
    gender: "unisex",
    price: 220,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Ink", hex: "#0A0A0B" },
    ],
    primaryHex: "#D7FF1E",
    image: img("kat-runner-volt"),
    imageAlt: "Kat Runner 02 in volt, dark studio shot, three-quarter angle.",
    badge: "new-drop",
    popularity: 98,
    releasedAt: "2026-05-12",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Daily mile, full carbon plate, volt sole.",
    weightGrams: 248,
    drop: 8,
  },
  {
    id: "p-002",
    slug: "kat-trail-monolith",
    name: "Kat Trail Monolith",
    brand: "katooni",
    category: "trail",
    gender: "unisex",
    price: 245,
    currency: "USD",
    colorways: [
      { name: "Slate", hex: "#3A3D44" },
      { name: "Volt", hex: "#D7FF1E" },
    ],
    primaryHex: "#3A3D44",
    image: img("kat-trail-monolith"),
    imageAlt: "Kat Trail Monolith in slate, rugged outsole, dark studio.",
    badge: null,
    popularity: 84,
    releasedAt: "2026-04-02",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Lugged 5 mm outsole, rock plate, gaiter-ready upper.",
    weightGrams: 312,
    drop: 6,
  },
  {
    id: "p-003",
    slug: "kat-track-spike",
    name: "Kat Track Spike",
    brand: "katooni",
    category: "track",
    gender: "unisex",
    price: 180,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Carbon", hex: "#161619" },
    ],
    primaryHex: "#161619",
    image: img("kat-track-spike"),
    imageAlt: "Kat Track Spike on dark, low-profile competition silhouette.",
    badge: "last-pairs",
    popularity: 71,
    releasedAt: "2026-03-10",
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    short: "Pebax spike plate, removable pyramid pins.",
    weightGrams: 132,
    drop: 4,
  },
  {
    id: "p-004",
    slug: "kat-court-leather",
    name: "Kat Court Leather",
    brand: "katooni",
    category: "court",
    gender: "unisex",
    price: 260,
    currency: "USD",
    colorways: [
      { name: "Bone", hex: "#E6E2D6" },
      { name: "Ink", hex: "#0A0A0B" },
    ],
    primaryHex: "#E6E2D6",
    image: img("kat-court-leather"),
    imageAlt: "Kat Court Leather in bone, full-grain upper, dark studio.",
    badge: "restock",
    popularity: 76,
    releasedAt: "2026-02-22",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Italian full-grain, hand-lasted, gum rubber outsole.",
    weightGrams: 388,
    drop: 0,
  },
  {
    id: "p-005",
    slug: "kat-knit-pulse",
    name: "Kat Knit Pulse",
    brand: "katooni",
    category: "lifestyle",
    gender: "unisex",
    price: 165,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Smoke", hex: "#1F1F24" },
      { name: "Bone", hex: "#E6E2D6" },
    ],
    primaryHex: "#1F1F24",
    image: img("kat-knit-pulse"),
    imageAlt: "Kat Knit Pulse in smoke, recycled knit upper, dark studio.",
    badge: "new-drop",
    popularity: 89,
    releasedAt: "2026-05-30",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Recycled knit, sock-fit collar, vulcanized cup sole.",
    weightGrams: 268,
    drop: 6,
  },
  {
    id: "p-006",
    slug: "kat-runner-pro",
    name: "Kat Runner Pro",
    brand: "katooni",
    category: "running",
    gender: "unisex",
    price: 285,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Carbon", hex: "#161619" },
    ],
    primaryHex: "#D7FF1E",
    image: img("kat-runner-pro"),
    imageAlt: "Kat Runner Pro in volt and carbon, race-day silhouette.",
    badge: null,
    popularity: 92,
    releasedAt: "2026-01-15",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Race-day carbon plate, supercritical foam, 4 mm drop.",
    weightGrams: 198,
    drop: 4,
  },
  {
    id: "p-007",
    slug: "kat-trail-storm",
    name: "Kat Trail Storm",
    brand: "katooni",
    category: "trail",
    gender: "unisex",
    price: 235,
    currency: "USD",
    colorways: [
      { name: "Ink", hex: "#0A0A0B" },
      { name: "Volt", hex: "#D7FF1E" },
    ],
    primaryHex: "#0A0A0B",
    image: img("kat-trail-storm"),
    imageAlt: "Kat Trail Storm in ink, all-weather upper, dark studio.",
    badge: null,
    popularity: 67,
    releasedAt: "2026-02-04",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "eVent membrane, reinforced toe, 4.5 mm lugs.",
    weightGrams: 328,
    drop: 6,
  },
  {
    id: "p-008",
    slug: "kat-court-low",
    name: "Kat Court Low",
    brand: "katooni",
    category: "court",
    gender: "unisex",
    price: 220,
    currency: "USD",
    colorways: [
      { name: "Ink", hex: "#0A0A0B" },
      { name: "Bone", hex: "#E6E2D6" },
    ],
    primaryHex: "#0A0A0B",
    image: img("kat-court-low"),
    imageAlt: "Kat Court Low in ink, low-top silhouette, dark studio.",
    badge: "restock",
    popularity: 58,
    releasedAt: "2025-11-08",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Suede and leather low-top, herringbone gum outsole.",
    weightGrams: 372,
    drop: 0,
  },
  {
    id: "p-009",
    slug: "kat-runner-cruiser",
    name: "Kat Runner Cruiser",
    brand: "katooni",
    category: "running",
    gender: "unisex",
    price: 195,
    currency: "USD",
    colorways: [
      { name: "Smoke", hex: "#1F1F24" },
      { name: "Volt", hex: "#D7FF1E" },
    ],
    primaryHex: "#1F1F24",
    image: img("kat-runner-cruiser"),
    imageAlt: "Kat Runner Cruiser in smoke, cushioned daily trainer.",
    badge: null,
    popularity: 81,
    releasedAt: "2026-03-20",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Max-cushion daily trainer, knit upper, 8 mm drop.",
    weightGrams: 286,
    drop: 8,
  },
  {
    id: "p-010",
    slug: "kat-knit-trail",
    name: "Kat Knit Trail",
    brand: "katooni",
    category: "trail",
    gender: "unisex",
    price: 205,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Slate", hex: "#3A3D44" },
    ],
    primaryHex: "#3A3D44",
    image: img("kat-knit-trail"),
    imageAlt: "Kat Knit Trail in slate, hybrid trail silhouette.",
    badge: "last-pairs",
    popularity: 49,
    releasedAt: "2025-12-12",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Hybrid road-to-trail knit, 3.5 mm lugs, sock-fit.",
    weightGrams: 274,
    drop: 6,
  },
  {
    id: "p-011",
    slug: "kat-court-mid",
    name: "Kat Court Mid",
    brand: "katooni",
    category: "court",
    gender: "unisex",
    price: 240,
    currency: "USD",
    colorways: [
      { name: "Bone", hex: "#E6E2D6" },
      { name: "Ink", hex: "#0A0A0B" },
    ],
    primaryHex: "#E6E2D6",
    image: img("kat-court-mid"),
    imageAlt: "Kat Court Mid in bone, mid-top silhouette, dark studio.",
    badge: null,
    popularity: 64,
    releasedAt: "2026-01-28",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Mid-cut leather, padded collar, vulcanized gum sole.",
    weightGrams: 412,
    drop: 0,
  },
  {
    id: "p-012",
    slug: "kat-lifestyle-cruise",
    name: "Kat Cruise",
    brand: "katooni",
    category: "lifestyle",
    gender: "unisex",
    price: 145,
    currency: "USD",
    colorways: [
      { name: "Bone", hex: "#E6E2D6" },
      { name: "Ink", hex: "#0A0A0B" },
      { name: "Volt", hex: "#D7FF1E" },
    ],
    primaryHex: "#0A0A0B",
    image: img("kat-lifestyle-cruise"),
    imageAlt: "Kat Cruise in ink, low-profile lifestyle sneaker.",
    badge: null,
    popularity: 73,
    releasedAt: "2026-04-18",
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Canvas upper, vulcanized sole, all-day comfort.",
    weightGrams: 296,
    drop: 0,
  },

  // ============================================================
  // NIKE
  // ============================================================
  {
    id: "p-101",
    slug: "nike-pegasus-41",
    name: "Nike Pegasus 41",
    brand: "nike",
    category: "running",
    gender: "unisex",
    price: 140,
    currency: "USD",
    colorways: [
      { name: "Black/White", hex: "#0A0A0B" },
      { name: "Volt", hex: "#D7FF1E" },
    ],
    primaryHex: "#0A0A0B",
    image: img("nike-pegasus-41"),
    imageAlt: "Nike Pegasus 41 in black and white, dark studio shot.",
    badge: null,
    popularity: 88,
    releasedAt: "2026-05-01",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "React foam, 10 mm drop, daily workhorse.",
    weightGrams: 286,
    drop: 10,
  },
  {
    id: "p-102",
    slug: "nike-vaporfly-3",
    name: "Nike Vaporfly 3",
    brand: "nike",
    category: "running",
    gender: "unisex",
    price: 260,
    currency: "USD",
    colorways: [
      { name: "Volt/Black", hex: "#D7FF1E" },
      { name: "Proto", hex: "#FF6B00" },
    ],
    primaryHex: "#D7FF1E",
    image: img("nike-vaporfly-3"),
    imageAlt: "Nike Vaporfly 3 in volt and black, race-day silhouette.",
    badge: "new-drop",
    popularity: 96,
    releasedAt: "2026-04-12",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "ZoomX + carbon plate, race-day, 8 mm drop.",
    weightGrams: 196,
    drop: 8,
  },
  {
    id: "p-103",
    slug: "nike-infinityrn-4",
    name: "Nike InfinityRN 4",
    brand: "nike",
    category: "running",
    gender: "unisex",
    price: 160,
    currency: "USD",
    colorways: [
      { name: "Black", hex: "#0A0A0B" },
      { name: "White", hex: "#F5F5F2" },
    ],
    primaryHex: "#0A0A0B",
    image: img("nike-infinityrn-4"),
    imageAlt: "Nike InfinityRN 4 in black, cushioned daily trainer.",
    badge: null,
    popularity: 72,
    releasedAt: "2026-02-08",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "ReactX foam, max cushion, soft rocker geometry.",
    weightGrams: 304,
    drop: 9,
  },
  {
    id: "p-104",
    slug: "nike-alphafly-3",
    name: "Nike Alphafly 3",
    brand: "nike",
    category: "running",
    gender: "unisex",
    price: 285,
    currency: "USD",
    colorways: [
      { name: "Volt", hex: "#D7FF1E" },
      { name: "Black/Volt", hex: "#161619" },
    ],
    primaryHex: "#D7FF1E",
    image: img("nike-alphafly-3"),
    imageAlt: "Nike Alphafly 3 in volt, marathon racer with Zoom pods.",
    badge: null,
    popularity: 91,
    releasedAt: "2026-01-22",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "ZoomX + carbon + Air Zoom pods, marathon racer.",
    weightGrams: 218,
    drop: 8,
  },
  {
    id: "p-105",
    slug: "nike-dunk-low",
    name: "Nike Dunk Low",
    brand: "nike",
    category: "lifestyle",
    gender: "unisex",
    price: 110,
    currency: "USD",
    colorways: [
      { name: "Black/White", hex: "#0A0A0B" },
      { name: "Panda", hex: "#F5F5F2" },
    ],
    primaryHex: "#0A0A0B",
    image: img("nike-dunk-low"),
    imageAlt: "Nike Dunk Low in black and white, classic low-top.",
    badge: "restock",
    popularity: 95,
    releasedAt: "2025-09-15",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Heritage basketball silhouette, leather upper.",
    weightGrams: 460,
    drop: 0,
  },
  {
    id: "p-106",
    slug: "nike-airmax-90",
    name: "Nike Air Max 90",
    brand: "nike",
    category: "lifestyle",
    gender: "unisex",
    price: 130,
    currency: "USD",
    colorways: [
      { name: "Infrared", hex: "#D62828" },
      { name: "Black", hex: "#0A0A0B" },
    ],
    primaryHex: "#0A0A0B",
    image: img("nike-airmax-90"),
    imageAlt: "Nike Air Max 90 in black with visible Air unit.",
    badge: null,
    popularity: 87,
    releasedAt: "2025-10-04",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Visible Air, classic TPU overlays, all-day comfort.",
    weightGrams: 420,
    drop: 0,
  },
  {
    id: "p-107",
    slug: "nike-airforce-1",
    name: "Nike Air Force 1 '07",
    brand: "nike",
    category: "lifestyle",
    gender: "unisex",
    price: 115,
    currency: "USD",
    colorways: [
      { name: "Triple White", hex: "#F5F5F2" },
      { name: "Triple Black", hex: "#0A0A0B" },
    ],
    primaryHex: "#F5F5F2",
    image: img("nike-airforce-1"),
    imageAlt: "Nike Air Force 1 in triple white, classic basketball silhouette.",
    badge: "restock",
    popularity: 99,
    releasedAt: "2025-08-20",
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "All-leather, Air-Sole unit, the original.",
    weightGrams: 470,
    drop: 0,
  },

  // ============================================================
  // ADIDAS
  // ============================================================
  {
    id: "p-201",
    slug: "adidas-ultraboost-23",
    name: "Adidas Ultraboost 23",
    brand: "adidas",
    category: "running",
    gender: "unisex",
    price: 190,
    currency: "USD",
    colorways: [
      { name: "Core Black", hex: "#0A0A0B" },
      { name: "Cloud White", hex: "#F5F5F2" },
    ],
    primaryHex: "#0A0A0B",
    image: img("adidas-ultraboost-23"),
    imageAlt: "Adidas Ultraboost 23 in core black, knit upper.",
    badge: null,
    popularity: 79,
    releasedAt: "2026-03-18",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "Boost midsole, Primeknit upper, 10 mm drop.",
    weightGrams: 320,
    drop: 10,
  },
  {
    id: "p-202",
    slug: "adidas-adizero-boston",
    name: "Adidas Adizero Boston 12",
    brand: "adidas",
    category: "running",
    gender: "unisex",
    price: 160,
    currency: "USD",
    colorways: [
      { name: "Core Black", hex: "#0A0A0B" },
      { name: "Lucid Red", hex: "#FF3B3B" },
    ],
    primaryHex: "#0A0A0B",
    image: img("adidas-adizero-boston"),
    imageAlt: "Adidas Adizero Boston 12 in core black, race-trainer.",
    badge: "new-drop",
    popularity: 84,
    releasedAt: "2026-05-22",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "Lightstrike Pro + carbon rods, tempo trainer.",
    weightGrams: 264,
    drop: 6,
  },
  {
    id: "p-203",
    slug: "adidas-samba-og",
    name: "Adidas Samba OG",
    brand: "adidas",
    category: "lifestyle",
    gender: "unisex",
    price: 100,
    currency: "USD",
    colorways: [
      { name: "Cloud White", hex: "#F5F5F2" },
      { name: "Core Black", hex: "#0A0A0B" },
    ],
    primaryHex: "#F5F5F2",
    image: img("adidas-samba-og"),
    imageAlt: "Adidas Samba OG in cloud white and black, classic low-top.",
    badge: "restock",
    popularity: 93,
    releasedAt: "2025-07-12",
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Indoor football classic, leather upper, gum sole.",
    weightGrams: 320,
    drop: 0,
  },
  {
    id: "p-204",
    slug: "adidas-gazelle",
    name: "Adidas Gazelle Indoor",
    brand: "adidas",
    category: "lifestyle",
    gender: "unisex",
    price: 110,
    currency: "USD",
    colorways: [
      { name: "Bold Orange", hex: "#FF5A1F" },
      { name: "Navy", hex: "#1A2B5E" },
    ],
    primaryHex: "#FF5A1F",
    image: img("adidas-gazelle"),
    imageAlt: "Adidas Gazelle Indoor in bold orange, suede upper.",
    badge: null,
    popularity: 81,
    releasedAt: "2025-11-28",
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Suede upper, translucent sole, terrace classic.",
    weightGrams: 310,
    drop: 0,
  },

  // ============================================================
  // ON
  // ============================================================
  {
    id: "p-301",
    slug: "on-cloudmonster",
    name: "On Cloudmonster",
    brand: "on",
    category: "running",
    gender: "unisex",
    price: 170,
    currency: "USD",
    colorways: [
      { name: "Eclipse", hex: "#161619" },
      { name: "Frost", hex: "#DDE2E8" },
    ],
    primaryHex: "#161619",
    image: img("on-cloudmonster"),
    imageAlt: "On Cloudmonster in eclipse, max-cushion trainer.",
    badge: null,
    popularity: 78,
    releasedAt: "2026-02-14",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Max CloudTec, engineered mesh, 6 mm drop.",
    weightGrams: 295,
    drop: 6,
  },
  {
    id: "p-302",
    slug: "on-cloudflow-4",
    name: "On Cloudflow 4",
    brand: "on",
    category: "running",
    gender: "unisex",
    price: 150,
    currency: "USD",
    colorways: [
      { name: "White/Black", hex: "#F5F5F2" },
      { name: "Eclipse", hex: "#161619" },
    ],
    primaryHex: "#F5F5F2",
    image: img("on-cloudflow-4"),
    imageAlt: "On Cloudflow 4 in white and black, tempo trainer.",
    badge: "new-drop",
    popularity: 75,
    releasedAt: "2026-05-15",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Helion foam + CloudTec, fast and bouncy.",
    weightGrams: 246,
    drop: 6,
  },
  {
    id: "p-303",
    slug: "on-roger-clubhouse",
    name: "On Roger Clubhouse",
    brand: "on",
    category: "lifestyle",
    gender: "unisex",
    price: 130,
    currency: "USD",
    colorways: [
      { name: "White", hex: "#F5F5F2" },
      { name: "Sand", hex: "#D4C5A9" },
    ],
    primaryHex: "#F5F5F2",
    image: img("on-roger-clubhouse"),
    imageAlt: "On Roger Clubhouse in white, lifestyle court silhouette.",
    badge: null,
    popularity: 70,
    releasedAt: "2026-01-10",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Clean leather court, signature CloudTec sole.",
    weightGrams: 340,
    drop: 0,
  },

  // ============================================================
  // ASICS
  // ============================================================
  {
    id: "p-401",
    slug: "asics-novablast-4",
    name: "Asics Novablast 4",
    brand: "asics",
    category: "running",
    gender: "unisex",
    price: 140,
    currency: "USD",
    colorways: [
      { name: "Black/White", hex: "#0A0A0B" },
      { name: "Electric Blue", hex: "#3A7BD5" },
    ],
    primaryHex: "#0A0A0B",
    image: img("asics-novablast-4"),
    imageAlt: "Asics Novablast 4 in black, max-cushion trainer.",
    badge: null,
    popularity: 73,
    releasedAt: "2026-04-04",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "FF Blast Plus Eco, trampoline-like ride, 8 mm drop.",
    weightGrams: 274,
    drop: 8,
  },
  {
    id: "p-402",
    slug: "asics-gel-nimbus-26",
    name: "Asics Gel-Nimbus 26",
    brand: "asics",
    category: "running",
    gender: "unisex",
    price: 160,
    currency: "USD",
    colorways: [
      { name: "Black", hex: "#0A0A0B" },
      { name: "White", hex: "#F5F5F2" },
    ],
    primaryHex: "#0A0A0B",
    image: img("asics-gel-nimbus-26"),
    imageAlt: "Asics Gel-Nimbus 26 in black, plush daily trainer.",
    badge: "restock",
    popularity: 77,
    releasedAt: "2025-12-05",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "FF Blast Plus Eco + PureGEL, plush long-run shoe.",
    weightGrams: 290,
    drop: 8,
  },
  {
    id: "p-403",
    slug: "asics-metaspd-2",
    name: "Asics Metaspeed Sky+",
    brand: "asics",
    category: "track",
    gender: "unisex",
    price: 250,
    currency: "USD",
    colorways: [
      { name: "Yellow/Black", hex: "#D7FF1E" },
      { name: "White", hex: "#F5F5F2" },
    ],
    primaryHex: "#D7FF1E",
    image: img("asics-metaspd-2"),
    imageAlt: "Asics Metaspeed Sky+ in yellow and black, racing flat.",
    badge: null,
    popularity: 68,
    releasedAt: "2026-03-12",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45],
    short: "FF Turbo Plus plate, max cushion, marathon racer.",
    weightGrams: 184,
    drop: 5,
  },

  // ============================================================
  // NEW BALANCE
  // ============================================================
  {
    id: "p-501",
    slug: "nb-1080v13",
    name: "New Balance Fresh Foam 1080v13",
    brand: "newbalance",
    category: "running",
    gender: "unisex",
    price: 165,
    currency: "USD",
    colorways: [
      { name: "Black", hex: "#0A0A0B" },
      { name: "Slate", hex: "#3A3D44" },
    ],
    primaryHex: "#0A0A0B",
    image: img("nb-1080v13"),
    imageAlt: "New Balance 1080v13 in black, plush daily trainer.",
    badge: null,
    popularity: 80,
    releasedAt: "2026-04-20",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "Fresh Foam X, soft and stable, 8 mm drop.",
    weightGrams: 286,
    drop: 8,
  },
  {
    id: "p-502",
    slug: "nb-fuelcell-rebel",
    name: "New Balance FuelCell Rebel v4",
    brand: "newbalance",
    category: "running",
    gender: "unisex",
    price: 140,
    currency: "USD",
    colorways: [
      { name: "Electric Blue", hex: "#3A7BD5" },
      { name: "Black", hex: "#0A0A0B" },
    ],
    primaryHex: "#3A7BD5",
    image: img("nb-fuelcell-rebel"),
    imageAlt: "New Balance FuelCell Rebel v4 in electric blue, tempo trainer.",
    badge: "new-drop",
    popularity: 82,
    releasedAt: "2026-05-05",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "FuelCell midsole, energetic tempo ride, 6 mm drop.",
    weightGrams: 232,
    drop: 6,
  },
  {
    id: "p-503",
    slug: "nb-990v6",
    name: "New Balance 990v6 Made in USA",
    brand: "newbalance",
    category: "lifestyle",
    gender: "unisex",
    price: 200,
    currency: "USD",
    colorways: [
      { name: "Grey", hex: "#8E8E8E" },
      { name: "Black", hex: "#0A0A0B" },
    ],
    primaryHex: "#8E8E8E",
    image: img("nb-990v6"),
    imageAlt: "New Balance 990v6 in grey, premium Made in USA lifestyle.",
    badge: null,
    popularity: 88,
    releasedAt: "2026-02-26",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Pigskin + mesh, ENCAP midsole, Made in USA.",
    weightGrams: 410,
    drop: 0,
  },
  {
    id: "p-504",
    slug: "nb-2002r-protection",
    name: "New Balance 2002R Protection Pack",
    brand: "newbalance",
    category: "lifestyle",
    gender: "unisex",
    price: 170,
    currency: "USD",
    colorways: [
      { name: "Rain Cloud", hex: "#A8A8A4" },
      { name: "Black", hex: "#0A0A0B" },
    ],
    primaryHex: "#A8A8A4",
    image: img("nb-2002r-protection"),
    imageAlt: "New Balance 2002R Protection Pack in rain cloud, suede + mesh.",
    badge: null,
    popularity: 76,
    releasedAt: "2026-01-18",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    short: "Suede + mesh, ABZORB + N-ergy, technical lifestyle.",
    weightGrams: 420,
    drop: 0,
  },

  // ============================================================
  // HOKA
  // ============================================================
  {
    id: "p-601",
    slug: "hoka-clifton-9",
    name: "Hoka Clifton 9",
    brand: "hoka",
    category: "running",
    gender: "unisex",
    price: 145,
    currency: "USD",
    colorways: [
      { name: "Black/White", hex: "#0A0A0B" },
      { name: "Free People", hex: "#FF6B6B" },
    ],
    primaryHex: "#0A0A0B",
    image: img("hoka-clifton-9"),
    imageAlt: "Hoka Clifton 9 in black and white, max-cushion daily.",
    badge: "restock",
    popularity: 86,
    releasedAt: "2025-11-20",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "CMEVA midsole, light max-cushion, 5 mm drop.",
    weightGrams: 248,
    drop: 5,
  },
  {
    id: "p-602",
    slug: "hoka-mach-6",
    name: "Hoka Mach 6",
    brand: "hoka",
    category: "running",
    gender: "unisex",
    price: 140,
    currency: "USD",
    colorways: [
      { name: "Black/Volt", hex: "#0A0A0B" },
      { name: "Ice Flow", hex: "#DDE2E8" },
    ],
    primaryHex: "#0A0A0B",
    image: img("hoka-mach-6"),
    imageAlt: "Hoka Mach 6 in black, fast and light tempo trainer.",
    badge: "new-drop",
    popularity: 81,
    releasedAt: "2026-05-26",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "PROFLY+ construction, energetic tempo ride, 5 mm drop.",
    weightGrams: 232,
    drop: 5,
  },
  {
    id: "p-603",
    slug: "hoka-speedgoat-5",
    name: "Hoka Speedgoat 5",
    brand: "hoka",
    category: "trail",
    gender: "unisex",
    price: 155,
    currency: "USD",
    colorways: [
      { name: "Black/Volt", hex: "#0A0A0B" },
      { name: "Mountain View", hex: "#3A7BD5" },
    ],
    primaryHex: "#0A0A0B",
    image: img("hoka-speedgoat-5"),
    imageAlt: "Hoka Speedgoat 5 in black, all-terrain trail runner.",
    badge: null,
    popularity: 79,
    releasedAt: "2026-03-08",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    short: "Vibram Megagrip outsole, 5 mm lugs, all-terrain.",
    weightGrams: 304,
    drop: 5,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedDrop(): Product {
  // The new-drop with the highest popularity is the current featured drop.
  const newDrops = products.filter((p) => p.badge === "new-drop");
  const pool = newDrops.length > 0 ? newDrops : products;
  return [...pool].sort((a, b) => b.popularity - a.popularity)[0];
}

// Store preview slots are pinned to specific slugs so the four generated
// store-preview-{1..4}.png shots land in the homepage grid in order.
const STORE_PREVIEW_SLUGS = [
  "kat-runner-volt",
  "kat-runner-cruiser",
  "kat-court-leather",
  "nike-vaporfly-3",
] as const;

const STORE_PREVIEW_OVERRIDES: Record<string, string> = {
  "kat-court-leather": "/images/store-preview-3.png",
  "nike-vaporfly-3": "/images/store-preview-4.png",
};

export function getStorePreview(): Product[] {
  return STORE_PREVIEW_SLUGS.map((slug) => {
    const p = products.find((x) => x.slug === slug);
    if (!p) throw new Error(`getStorePreview: missing slug ${slug}`);
    return STORE_PREVIEW_OVERRIDES[slug]
      ? { ...p, image: STORE_PREVIEW_OVERRIDES[slug] }
      : p;
  });
}
